### ISSUE TITLE
New directory with name equals to Parent directory 

### ISSUE THREAD

**Issue by wilsonarteaga** [th-schwarz/C5Connector.Java#41]
Sorry for my English...
Problem:
When i create a new directory with name AAA inside another with the same name, the file tree display in the child folder, the contents of the parent folder.
Example:
AAA
-----file.png
-----AAA
----------file.png
----------AAA
...
...
...
 
![filemanager-bug](https://cloud.githubusercontent.com/assets/1974657/13224858/b7bebede-d98a-11e5-9268-528b2707f825.png)

I try to solve the problem.
In the file,

[C5Connector.Java/src/main/java/codes/thischwa/c5c/requestcycle/response/mode/FileInfo.java](url)

comment the line 69.

Change this:
![line-problem](https://cloud.githubusercontent.com/assets/1974657/13225237/437e7aee-d98c-11e5-85fa-8f59cc30582c.png)

For this:
![solved-problem](https://cloud.githubusercontent.com/assets/1974657/13225244/48e469da-d98c-11e5-8a29-8f8c9116150d.png)

I don't know if my change produces another errors in the application.
For me this solved my problem.

**Comment by th-schwarz** [comment]
Thank you wilsonarteaga for report this bug. 
Release is coming soon ...
